# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c191472bb49798cdb2736ec59c35b852af8fa43a526c10072db61450d933452a6295659f168f2b934ccb36b98143982c447e2f9839251432241bb788eaaa7d5

test:
  secret_key_base: 02e5590d0c52a0139a6c71b0bf75c57295f568d215054fc5f7660a0a383c5242166337d0e0e8299de85b1ac19aa85f89b865ac01d9164d61395a2c306e405aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 02e5590d0c52a0139a6c71b0bf75c57295f568d215054fc5f7660a0a383c5242166337d0e0e8299de85b1ac19aa85f89b865ac01d9164d61395a2c306e405aebaa
